# File managed by pluginsync
sudo: false
language: go
go:
- 1.6.3
- 1.7.3
env:
  global:
  - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
  - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
  matrix:
  - TEST_TYPE=small
  - TEST_TYPE=build
matrix:
  exclude:
  - go: 1.6.3
    env: TEST_TYPE=build
before_install:
- "[[ -d $SNAP_PLUGIN_SOURCE ]] || mkdir -p $ORG_PATH && ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE"
install:
- cd $SNAP_PLUGIN_SOURCE
- make deps
script:
- make check 2>&1
notifications:
  email: false
  slack:
    secure: VkbZLIc2RH8yf3PtIAxUNPdAu3rQQ7yQx0GcK124JhbEnZGaHyK615V0rbG7HcVmYKGPdB0cXqZiLBDKGqGKb2zR1NepOe1nF03jxGSpPq8jIFeEXSJGEYGL34ScDzZZGuG6qwbjFcXiW5lqn6t8igzp7v2+URYBaZo5ktCS2xY=
before_deploy:
- "./scripts/pre_deploy.sh"
deploy:
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: 08unkPHF+4qPiEHWhzUjrHnXbgr9W2CEZwgVFz+THrVgG0p11U4HgeXZBnTxc8kcbribiqgl6m3aglZDX8il8i39GwMljoTTy1w+WKR/+/rTX9q/06zPcUEyWQoFQUwQbTGXjIn00gypH08YAHkI61KT8+Ab84wTMAbDoRwsOU+iLuwru2Y8YQhvZfiSzsaR4vhnTLuGeq9WOFa4sgg0NOJgGZyqjeqVxGFzZ3fxX1JBd5e5Pulk+7f027rVALR3a5otnTfg5EKaRw4ZXGDENYzVpUl6YcpZcCFohpOQJi9XFwsyqIyS17y53vRzuz4fWSAcfzDl0sGOiKlGuDKJwDcByLkvgclPjFLPCouQoP3edKpGVILWfPXHT5fcY/gMQuHe7BgV0v+iwF5ZzuYh4sl/0XBlMsu3PZmrdYZ4cdXdHXpbl3HAHLMERD6GNd1Q/myUKClGEWf0oG5NTZXoqv98cVwTQwHnnLWdJIhcjKQIZ/IT19HhLKLB0sv3pNmrbuuHsAwj1qYfvoSVgv3nz4T8hAi5j2zQErYzhlV3rS1RgCiiEfE/1ibgtJNs2+ytGBsOCbPK8hJEBUZjVEsxtwGH2EAL6KddpklNhASHMCX4QsTw/zZBK6BvW4J5wDU5QW/ZDPXjZtYaTcJ+ZPqr/irfOq7aKTve8N4hn7aZVlA=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-publisher-heapster
    branch: master
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.3"
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: 08unkPHF+4qPiEHWhzUjrHnXbgr9W2CEZwgVFz+THrVgG0p11U4HgeXZBnTxc8kcbribiqgl6m3aglZDX8il8i39GwMljoTTy1w+WKR/+/rTX9q/06zPcUEyWQoFQUwQbTGXjIn00gypH08YAHkI61KT8+Ab84wTMAbDoRwsOU+iLuwru2Y8YQhvZfiSzsaR4vhnTLuGeq9WOFa4sgg0NOJgGZyqjeqVxGFzZ3fxX1JBd5e5Pulk+7f027rVALR3a5otnTfg5EKaRw4ZXGDENYzVpUl6YcpZcCFohpOQJi9XFwsyqIyS17y53vRzuz4fWSAcfzDl0sGOiKlGuDKJwDcByLkvgclPjFLPCouQoP3edKpGVILWfPXHT5fcY/gMQuHe7BgV0v+iwF5ZzuYh4sl/0XBlMsu3PZmrdYZ4cdXdHXpbl3HAHLMERD6GNd1Q/myUKClGEWf0oG5NTZXoqv98cVwTQwHnnLWdJIhcjKQIZ/IT19HhLKLB0sv3pNmrbuuHsAwj1qYfvoSVgv3nz4T8hAi5j2zQErYzhlV3rS1RgCiiEfE/1ibgtJNs2+ytGBsOCbPK8hJEBUZjVEsxtwGH2EAL6KddpklNhASHMCX4QsTw/zZBK6BvW4J5wDU5QW/ZDPXjZtYaTcJ+ZPqr/irfOq7aKTve8N4hn7aZVlA=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-publisher-heapster
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.3"
- provider: releases
  api_key:
    secure: gI9c0XNUt0Mw/5Fe54JKoR4c+Vux2Qefe9Tz2QrRse9qLf/71XVo4ZVfWtGRIkwyIU2VMOdo6sryd7JO1DcyKuXy/l7/uDhLUvtAR6DolCfIAH47BUA77vb0mRU2B3ybIHDz5kfugULb4r7LTA6U9utgC2nvm2BQhgipoVwo3WuXXTd/pcFxtlmN0G2itZOqe9Pm2smTnhtulP+GQ3UUK/OWWFl3cuAaSNHlyQvmurpMoMCuAGjpswRn6fZUCeG2rBgh/IhhuGGu6628r+j1BTIJp+DGrBgJeMKYNIcTIy8NIpJ+vgwey9wGiGV8E0M+vm+8ApuOXzurvDdw2KoLVeuUDbw+aElo7hB2sT/UhITvJs6eE8gRDUSUtThX6t03gdjleMHjz2UxtLdO825zRm2M4rV7mDr1LsaFkBGa/TzU0STlnDXlXcriBwel6MCH45X3IcpW+KrTQ5g1mYSoC3RVcqOqu/BIRgP240e2BG0Gg7WKBhQkvmMw3cfM7G7sjWsg+nIGn24WROuEScV66Fd9imr+O5YKMWNFa835cEyPXXG6VmJBJgALfao8i4zSOx+AgF6Ver76sDqewVKokANi2yoLg27UeJnEcERZQgbKWDJHdmPHKcLQEsJje8PkuxRPVUXSD2XLCw4a2fuH1fSV08lu9piLnaBpY78lbDA=
  file:
    - release/snap-plugin-publisher-heapster_linux_x86_64
  skip_cleanup: true
  on:
    repo: intelsdi-x/snap-plugin-publisher-heapster
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.3"
